/**
 * Constants for ClickHouse language detection, keywords, and data types.
 */

export const CH_DETECTION_PATTERNS: RegExp[] = [
    /ENGINE\s*=\s*(MergeTree|ReplicatedMergeTree|ReplacingMergeTree|SummingMergeTree|AggregatingMergeTree|CollapsingMergeTree|VersionedCollapsingMergeTree|GraphiteMergeTree|Distributed|Buffer|TinyLog|StripeLog)\s*[\(\s;]/i,
    /\bPREWHERE\b/i,
    /\bLIMIT\s+\d+\s+BY\b/i,
    /\bWITH\s+TOTALS\b/i,
    /\bWITH\s+ROLLUP\b/i,
    /\bWITH\s+CUBE\b/i,
    /\bARRAY\s+JOIN\b/i,
    /\bGLOBAL\s+(NOT\s+)?IN\b/i,
    /\bASOf\s+JOIN\b/i,
    /\bFORMAT\s+(TabSeparated|JSONEachRow|JSONCompact|Parquet|Arrow|ORC|Avro|RowBinary|Native|PrettyCompact|Pretty|CSV|CSVWithNames|LineAsString|RawBLOB)\b/i,
    /\b(UInt8|UInt16|UInt32|UInt64|UInt128|UInt256|Int128|Int256|Float32|Float64)\b/,
    /\bDateTime64\s*\(/i,
    /\btoDateTime64\s*\(/i,
    /\bLowCardinality\s*\(/i,
    /\bFixedString\s*\(/i,
    /\bAggregateFunction\s*\(/i,
    /\bSimpleAggregateFunction\s*\(/i,
    /\b(groupArray|groupUniqArray|groupArrayInsertAt|groupBitmap)\s*\(/i,
    /\barrayJoin\s*\(/i,
    /\b(windowFunnel|sequenceMatch|sequenceCount|retention)\s*\(/i,
    /\b(dictGet|dictGetOrDefault|dictHas)\s*\(/i,
    /\b(uniqExact|uniqHLL12|uniqCombined|uniqTheta)\s*\(/i,
    /\b(argMin|argMax)\s*\(/i,
    /\b(topK|topKWeighted)\s*\(/i,
    /\b(quantileTDigest|quantileTiming|quantileDeterministic)\s*\(/i,
    /\b(toYYYYMM|toYYYYMMDD|toStartOfInterval|toRelativeHourNum)\s*\(/i,
    /\b(parseDateTimeBestEffort|formatReadableSize|formatReadableQuantity)\s*\(/i,
    /\b(accurateCast|accurateCastOrNull|bitCast|reinterpretAs)\s*\(/i,
    /\b(generateUUIDv4|generateUUIDv7|UUIDStringToNum|UUIDNumToString)\s*\(/i,
    /\)\s*SETTINGS\s+\w+\s*=/i,
    /\bTTL\s+\w+.*\+\s*INTERVAL\b/i,
    /\bCODEC\s*\(\s*(Delta|Gorilla|ZSTD|LZ4|LZ4HC|DoubleDelta|FPC|T64)\b/i,
    /\bSAMPLE\s+BY\b/i,
    /\bFROM\s+system\.(tables|columns|functions|databases|merges|mutations|parts|replicas|query_log|processes)\b/i,
    /\bON\s+CLUSTER\s+\w+/i,
];

export const CH_KEYWORDS = [
    'SELECT', 'DISTINCT', 'FROM', 'WHERE', 'GROUP BY', 'ORDER BY', 'HAVING',
    'LIMIT', 'LIMIT BY', 'OFFSET', 'UNION ALL', 'UNION', 'INTERSECT', 'EXCEPT',
    'JOIN', 'INNER JOIN', 'LEFT JOIN', 'RIGHT JOIN', 'FULL JOIN', 'CROSS JOIN',
    'ARRAY JOIN', 'LEFT ARRAY JOIN', 'ASOF JOIN', 'SEMI JOIN', 'ANTI JOIN',
    'LEFT SEMI JOIN', 'RIGHT SEMI JOIN', 'LEFT ANTI JOIN', 'RIGHT ANTI JOIN',
    'GLOBAL IN', 'GLOBAL NOT IN', 'PREWHERE', 'SAMPLE', 'FINAL', 'FORMAT',
    'SETTINGS', 'WITH TOTALS', 'WITH ROLLUP', 'WITH CUBE', 'WITH FILL',
    'WITH', 'OVER', 'PARTITION BY', 'WINDOW', 'ROWS', 'RANGE',
    'INSERT INTO', 'VALUES', 'CREATE TABLE', 'ALTER TABLE', 'DROP TABLE',
    'TRUNCATE TABLE', 'CREATE VIEW', 'CREATE MATERIALIZED VIEW',
    'CREATE DICTIONARY', 'CREATE TEMPORARY TABLE', 'CREATE LIVE VIEW',
    'ATTACH TABLE', 'DETACH TABLE', 'RENAME TABLE', 'EXCHANGE TABLES',
    'OPTIMIZE TABLE', 'CHECK TABLE', 'REPAIR TABLE',
    'DESCRIBE TABLE', 'SHOW CREATE TABLE', 'SHOW DATABASES', 'SHOW TABLES',
    'SHOW PROCESSLIST', 'SHOW SETTINGS', 'EXISTS TABLE', 'EXISTS DATABASE',
    'KILL QUERY', 'KILL MUTATION', 'SYSTEM FLUSH LOGS',
    'SYSTEM RELOAD DICTIONARIES', 'SYSTEM RELOAD MODELS',
    'SYSTEM DROP QUERY CACHE', 'SYSTEM SYNC REPLICA',
    'ON CLUSTER', 'ENGINE', 'PARTITION BY', 'ORDER BY', 'PRIMARY KEY',
    'SAMPLE BY', 'TTL', 'CODEC', 'DEDUPLICATE', 'REPLACE', 'AS',
    'NOT NULL', 'DEFAULT', 'MATERIALIZED', 'ALIAS', 'EPHEMERAL',
    'COMMENT', 'IF NOT EXISTS', 'IF EXISTS', 'OR REPLACE',
    'TO', 'FROM INFILE', 'INTO OUTFILE', 'TABLE', 'DATABASE',
    'DICTIONARY', 'FUNCTION', 'LAYOUT', 'SOURCE', 'LIFETIME',
    'LIFETIME(MIN', 'LIFETIME(MAX', 'RANGE', 'MIN', 'MAX',
    'INSERT', 'UPDATE', 'DELETE', 'SET', 'WHERE',
    'AND', 'OR', 'NOT', 'IN', 'NOT IN', 'EXISTS', 'BETWEEN',
    'LIKE', 'NOT LIKE', 'ILIKE', 'NOT ILIKE', 'REGEXP',
    'CASE', 'WHEN', 'THEN', 'ELSE', 'END',
    'IS NULL', 'IS NOT NULL', 'COALESCE', 'IFNULL', 'NULLIF',
    'TRUE', 'FALSE', 'NULL',
    'ASC', 'DESC', 'NULLS FIRST', 'NULLS LAST',
    'ALL', 'ANY', 'SOME', 'FIRST', 'LAST',
    'CAST', 'AS', 'INTERVAL', 'EXTRACT',
    'toInt8', 'toInt16', 'toInt32', 'toInt64', 'toInt128', 'toInt256',
    'toUInt8', 'toUInt16', 'toUInt32', 'toUInt64', 'toUInt128', 'toUInt256',
    'toFloat32', 'toFloat64', 'toDecimal', 'toDecimal32', 'toDecimal64', 'toDecimal128',
    'toDate', 'toDateTime', 'toDateTime64', 'toString',
    'MergeTree', 'ReplacingMergeTree', 'SummingMergeTree', 'AggregatingMergeTree',
    'CollapsingMergeTree', 'VersionedCollapsingMergeTree', 'GraphiteMergeTree',
    'ReplicatedMergeTree', 'ReplicatedReplacingMergeTree',
    'ReplicatedSummingMergeTree', 'ReplicatedAggregatingMergeTree',
    'ReplicatedCollapsingMergeTree', 'ReplicatedVersionedCollapsingMergeTree',
    'ReplicatedGraphiteMergeTree',
    'Distributed', 'Memory', 'Buffer', 'Set', 'Join',
    'File', 'Null', 'View', 'MaterializedView', 'LiveView',
    'URL', 'Kafka', 'EmbeddedRocksDB', 'RabbitMQ',
    'PostgreSQL', 'MySQL', 'MongoDB', 'HDFS', 'S3',
    'generateUUIDv4', 'generateUUIDv7', 'now', 'today', 'yesterday',
];

export const CH_DATA_TYPES = [
    'UInt8', 'UInt16', 'UInt32', 'UInt64', 'UInt128', 'UInt256',
    'Int8', 'Int16', 'Int32', 'Int64', 'Int128', 'Int256',
    'Float32', 'Float64', 'Decimal', 'Decimal32', 'Decimal64', 'Decimal128', 'Decimal256',
    'String', 'FixedString', 'UUID', 'IPv4', 'IPv6',
    'Date', 'Date32', 'DateTime', 'DateTime64',
    'Array', 'Tuple', 'Map', 'Nested', 'Set',
    'Nullable', 'LowCardinality',
    'AggregateFunction', 'SimpleAggregateFunction',
    'Enum8', 'Enum16', 'Bool', 'Nothing',
    'IntervalSecond', 'IntervalMinute', 'IntervalHour',
    'IntervalDay', 'IntervalWeek', 'IntervalMonth',
    'IntervalQuarter', 'IntervalYear',
    'Point', 'Ring', 'Polygon', 'MultiPolygon',
    'JSON', 'Dynamic', 'Variant',
    'BFloat16',
];
